### PR TITLE
Remove unnecessary dependency on positioning-private

### PR DESCRIPTION
**Pull request by dirkhh**
The module compiles fine without it (and looking through the sources doesn't
appear to pull in any private headers from qtpositioning).

Signed-off-by: Dirk Hohndel <dirk@hohndel.org>

### CODE REVIEW

**Comment by neolit123** [comment]
hi, @vladest. @dirkhh 

we've just discussed this on the mailing list.
are we sure that `positioning-private` is not a dependency? i'm now i'm getting this error with Qt 5.9.0 on Windows:

```
In file included from ./QtLocation/private/qgeotiledmap_p.h:53:0,
                 from QtLocation/private/qgeotiledmappingmanagerengine_p.h:58,
                 from qgeotiledmappingmanagerenginegooglemaps.h:4,
                 from qgeoserviceproviderplugingooglemaps.cpp:5:
./QtLocation/private/qgeomap_p.h:55:53: fatal error: QtPositioning/private/qdoublevector2d_p.h: No such file or directory
```

`qgeomap_p.h` does have this include:
`#include <QtPositioning/private/qdoublevector2d_p.h>`

**Comment by dirkhh** [comment]
I'm sad to say that it seems @neolit123 is correct - in my testing I removed the package that pulled the private headers, but for some reason they stayed in the file system, so my testing was invalid.
It seemed so logical, since you didn't include anything directly.

My apologies for the bad PR, please revert :-(
